name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml and HTML files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          source: "docker-compose.yml,html"
          target: "/home/ubuntu/nginx-deploy"

      - name: Deploy with Docker Compose (Handling Port Conflicts)
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/nginx-deploy
            
            # Modify docker-compose.yml to use port 8080 instead of 80
            sed -i 's/- "80:80"/- "8080:80"/' docker-compose.yml
            
            # Check if docker-compose is installed
            if ! command -v docker-compose &> /dev/null; then
              echo "Docker Compose not found, installing..."
              sudo apt-get update
              sudo apt-get install -y docker-compose
            fi
            
            # Stop and remove existing containers
            docker-compose down
            
            # Start containers with the new port configuration
            docker-compose up -d
            
            echo "Deployment completed successfully. Nginx is now running on port 8080."
            echo "You can access it at http://your-server-ip:8080"